# Generated by Django 5.1 on 2026-06-30 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_pic', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fb_post.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_post.post')),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_post.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('WOW', 'WOW'), ('LIT', 'LIT'), ('LOVE', 'LOVE'), ('HAHA', 'HAHA'), ('THUMBS-UP', 'THUMBS-UP'), ('THUMBS-DOWN', 'THUMBS-DOWN'), ('ANGRY', 'ANGRY'), ('SAD', 'SAD')], max_length=100)),
                ('reacted_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fb_post.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fb_post.post')),
                ('reacted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_post.user')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_post.user'),
        ),
    ]
