# Generated by Django 5.1 on 2026-07-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_post', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', True)), fields=('reacted_by', 'post'), name='unique_post_reaction_per_user'),
        ),
    ]
